### ISSUE TITLE
Layout issue in the latest ERP version on the dev system

### ISSUE THREAD

**Issue by TobiNeo** [atlas-aero/erpnext_hr_time#23]
There is an issue in the HR module with the layout of  the "Employees Present"
![Screenshot 2024-03-05 180048](https://github.com/atlas-aero/erpnext_hr_time/assets/114566202/9a0b18ca-3f54-413f-b117-d02c6c6af793)

**Comment by marius-meissner** [comment]
@TobiNeo Fix was released in version 15.0.0, which has been deployed to staging server.
Please verify if the issue has been fixed.
